import type { MetroStation } from "./types";

/**
 * Реальные станции метро, МЦД и МЦК в центре Москвы.
 * Координаты — [долгота, широта].
 */
export const MOSCOW_METRO_STATIONS: MetroStation[] = [
  // Метро
  {
    id: "metro-001",
    name: "Тверская",
    kind: "metro",
    lines: ["Замоскворецкая"],
    coordinates: [37.6047, 55.7656],
    address: "Тверская ул.",
    description: "Станция Замоскворецкой линии, пересадка на Пушкинскую",
  },
  {
    id: "metro-002",
    name: "Пушкинская",
    kind: "metro",
    lines: ["Таганско-Краснопресненская", "Сокольническая"],
    coordinates: [37.6067, 55.7657],
    address: "Страстной бульвар",
    description: "Пересадочный узел в центре города",
  },
  {
    id: "metro-003",
    name: "Чистые пруды",
    kind: "metro",
    lines: ["Сокольническая", "Калужско-Рижская"],
    coordinates: [37.6389, 55.7649],
    address: "Чистопрудный бульвар",
    description: "Станция у Чистопрудного бульвара",
  },
  {
    id: "metro-004",
    name: "Кропоткинская",
    kind: "metro",
    lines: ["Сокольническая"],
    coordinates: [37.6039, 55.745],
    address: "ул. Большая Пироговская",
    description: "Станция у храма Христа Спасителя и Парка Горького",
  },
  {
    id: "metro-005",
    name: "Курская",
    kind: "metro",
    lines: ["Кольцевая", "Арбатско-Покровская"],
    coordinates: [37.6593, 55.7585],
    address: "Земляной Вал",
    description: "Пересадка на Курский вокзал",
  },
  {
    id: "metro-006",
    name: "Белорусская",
    kind: "metro",
    lines: ["Замоскворецкая", "Кольцевая"],
    coordinates: [37.5833, 55.7762],
    address: "пл. Тверская Застава",
    description: "Узел у Белорусского вокзала",
  },
  {
    id: "metro-007",
    name: "Арбатская",
    kind: "metro",
    lines: ["Арбатско-Покровская"],
    coordinates: [37.6034, 55.7522],
    address: "ул. Арбат",
    description: "Станция на Арбате",
  },
  {
    id: "metro-008",
    name: "Парк культуры",
    kind: "metro",
    lines: ["Сокольническая", "Кольцевая"],
    coordinates: [37.5935, 55.7352],
    address: "Зубовский бульвар",
    description: "Станция у входа в Парк Горького",
  },
  {
    id: "metro-009",
    name: "Лубянка",
    kind: "metro",
    lines: ["Сокольническая"],
    coordinates: [37.6253, 55.7598],
    address: "ул. Мясницкая",
    description: "Станция в историческом центре",
  },
  {
    id: "metro-010",
    name: "Китай-город",
    kind: "metro",
    lines: ["Таганско-Краснопресненская", "Калужско-Рижская"],
    coordinates: [37.6315, 55.7555],
    address: "Славянская пл.",
    description: "Крупный пересадочный узел",
  },
  // МЦК
  {
    id: "mcc-001",
    name: "Площадь Гагарина",
    kind: "mcc",
    lines: ["МЦК"],
    coordinates: [37.583, 55.728],
    address: "Ленинский проспект",
    description: "Станция МЦК у МГУ",
  },
  {
    id: "mcc-002",
    name: "Крымская",
    kind: "mcc",
    lines: ["МЦК"],
    coordinates: [37.6045, 55.73],
    address: "Крымский Вал",
    description: "Станция МЦК у Парка Горького",
  },
  {
    id: "mcc-003",
    name: "Дубровка",
    kind: "mcc",
    lines: ["МЦК"],
    coordinates: [37.655, 55.718],
    address: "ул. Дубининская",
    description: "Станция МЦК на юго-востоке центра",
  },
  // МЦД
  {
    id: "mcd-001",
    name: "Белорусская",
    kind: "mcd",
    lines: ["МЦД-1", "МЦД-4"],
    coordinates: [37.583, 55.7765],
    address: "пл. Тверская Застава",
    description: "Остановка МЦД у Белорусского вокзала",
  },
  {
    id: "mcd-002",
    name: "Площадь трёх вокзалов",
    kind: "mcd",
    lines: ["МЦД-2", "МЦД-4"],
    coordinates: [37.652, 55.776],
    address: "Комсомольская пл.",
    description: "Остановка МЦД у Казанского и Ленинградского вокзалов",
  },
];
